---
title: "DS105M: Women In Parliament - Data"
author: AS, NC, LM
date: November 26, 2021
output:
  slidy_presentation: default
  ioslides_presentation: default
---

```{css echo=FALSE}
h1 {
text-align: center;
color:tomato;
font-size: 29px;
font-weight:bold;
align-self: center;
text-align: center;
}
div {font-size: 24px;
letter-spacing: 2px;
word-spacing: 2.5px;
text-decoration: none;
font-style: normal;
font-variant: normal;
text-transform: none;
padding-top: 20px;
}
ul, p {
padding: 1px 2% 1px;
max-height:90%
text-align: ltr;
font-weight: normal;
color: #1E1E1E;
}
* {background-color: #EDEDED;
background-size: 100%;
font-family: "Lucida Console", Monaco, monospace;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r packages, include=FALSE}
if(!require("pacman"))install.packages("pacman")

pacman::p_load("tidyverse", "reticulate", "here")
```


```{r data, include=FALSE}
#source(here("scripts", "download-csv-html.R")) # once you have run the script once, you can comment out this line by typing "#" in front of it. Doing this will mean the data loads directly from your local data_raw folder rather than downloading every time.

harvard <- read.csv(here("data_raw", "rawdata.csv"))
```
# Slide 1.1: Brief summary

# Slide 1.2: Organisation

# Slide 1.3: Workflow

# Slide 2.1: Obtaining the data

# Slide 2.2: Summary statistics

# Slide 2.3: Summary statistics on speeches

# Slide 2.4: Summary statistics on msps

# Slide 3.1: Data wrangling

# Slide 3.2: Analysis

# Slide 3.3: Visualisations planned
